### PR TITLE
Make DATETIME seconds optional and fractional seconds more flexible

### LINKED ISSUE #648: Question regarding the precision of DATETIME values
How should I understand

> ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ

when it comes to DATETIME values containing fractions of seconds? Is this very strict, in the sense that the precision must be milliseconds, not finer, not coarser?

Or are the following datetimes GeoPackage compliant as well?:
- 2023-02-22T16:00:00.1Z
- 2023-02-22T16:00:00.12Z
- 2023-02-22T16:00:00.1234Z
- 2023-02-22T16:00:00.12345Z

Note: similar questions have been asked in https://github.com/OSGeo/gdal/issues/3423.

### PR DESCRIPTION
**Pull request by jyutzler**
closes #648

### CODE REVIEW

**Comment by heidivanparys** [comment]
As far as I can see, a few additional changes would be needed. See https://github.com/opengeospatial/geopackage/commit/91afa1d0c16114dfa6a1fa673372e94be67f14d3.

**Comment by heidivanparys** [comment]
Could a warning be added regarding the precision of timestamps when using the built-in date and time functions? I know you're supposed to be familiar with SQLite when using GeoPackage, but certain things may be worth highlighting.

See https://github.com/opengeospatial/geopackage/commit/53b06c4835de066544418046708c7e3cc1278d88 for a proposal.

See also e.g. https://sqlite.org/forum/forumpost/8e66227e40a7e8bd for more background.

**Comment by jyutzler** [comment]
@heidivanparys can you make a new pull request from your fork? I can see your proposals but there is no great way for me to integrate them into the current branch.

**Comment by heidivanparys** [comment]
Sure, see #651. I made the pull request to the 648-datetime branch, I can change it to the master branch if that would be better.

**Comment by jyutzler** [comment]
> Sure, see #651. I made the pull request to the 648-datetime branch, I can change it to the master branch if that would be better.

That's perfect, thanks.

**Comment by jyutzler** [comment]
Closed by #653

**Pull request closed without merging**
