### PR TITLE
Adding R148/149 to enforce valid WKB envelope values

### PR DESCRIPTION
**Pull request by jyutzler**

### CODE REVIEW

**Comment by rouault** [comment]
The note below Requirement 15 currently mentions
```
The bounding box (min_x, min_y, max_x, max_y) provides an informative bounding box of the content. Applications may use this bounding box as the extents of a default view but there are no requirements that this bounding box be exact or represent the minimum bounding box of the content
```

This should be rephrased to be restricted to tiles only. This also means that people using previously gpkg_contents as a way of zooming in to some area of interest n a feature table, but having larger content, won't be able to do it anymore (not that I claim this is a real use case)

**Comment by jyutzler** [comment]
@rouault wrote:
> This should be rephrased to be restricted to tiles only.

What is your justification for this? I disagree with it. A feature _product_ should have its total extents in `gpkg_geometry_columns`, but the possibility should exist that it is only partially populated and the extents of the actual content can be presented in `gpkg_contents`.

**Comment by bosborn** [comment]
This is getting pretty confusing.  Are the NSG requirements starting to make their way into the base requirements?  Are we planning to require features to have populated contents ranges for features?

The geometry columns table does not contain min and max values.  Those are only determinable by the actual geometries contained within.

The pull request attempts to perform a query which is not valid as min_x, min_y, max_x, max_y are not columns within gpkg_geometry_columns.

```
SELECT table_name AS tn, column_name AS cn, min_x, min_y, max_x, max_y, FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type = 'features')
```

**Comment by rouault** [comment]
> A feature product should have its total extents in gpkg_geometry_columns

There is no spatial extent in gpkg_geometry_columns. They are only in gpkg_contents for vectors. Actually the proposed ATS doesn't work because of this

**Comment by jyutzler** [comment]
Ack, you guys are right. I wrote this too fast. OK, let me take another look at it.

**Comment by ajanett** [comment]
My suggestion would be something like:

Assumption: Must Pass Requirement #19
1. SELECT      table_name     AS      tn,       column_name     AS      cn       FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type = 'features')

2.  Not testable if returns an empty result set

3.  For  each row from step 1 
       a.  SELECT cn FROM tn
       b.  Not testable if none found
       c.  SELECT min_x, max_x, min_y, max_y from gpkg_contents WHERE table_name = tn
                i. Not testable if none found
	        ii. Fail if the gpkg_contents extents do not contain the feature envelope extents (specified within cn).

**Comment by jyutzler** [comment]
OK @rouault @bosborn please try it again.

**Comment by bosborn** [comment]
The SQL query looks better and executes.

Since the contents min and max columns are still nullable, and I don't see a requirement that features require them to be non nullable, I assume that a geometry is not considered outside the extents of the contents if the min/max ranges are null?
`falls outside the extents from gpkg_contents`

**Comment by ajanett** [comment]
I have not seen a feature geopackage that does not have extents in gpkg_contents.  But you make a good point.  Perhaps it would be a good idea to ensure the contents min/max columns are no longer nullable.  Please note that it is also possible that the feature geometry BLOB may have no envelope in which case this is not testable. Also if the requirement 19 does not pass, there is no reason to try and perform this test.

**Comment by rouault** [comment]
> I have not seen a feature geopackage that does not have extents in gpkg_contents.

I did! And it was a 81 GB large geopackage : ftp://rockyftp.cr.usgs.gov/ngtoc/hydro/outgoing/GeoPackage_hydrography_examples/whole_flattened_NHD_current/NHDPlusHR_flattened_20171103_gpkg_20171106.7z

**Comment by bosborn** [comment]
I have seen examples before produced by others, but we also try to run as many examples through our implementations as possible.  The contents extents have never been something we've been able to rely on existing.  For tiles, the tile matrix set ensures that we have the bounds we required.  They can also not be non nullable due to the fact that attributes, related tables, etc would then require them.

If the goal is to force this information to be there, then perhaps the geometry columns table should define and require them as non null in 1.3.0?

**Comment by jyutzler** [comment]
Since #443 was closed with no action required, this PR is OBE.

**Pull request closed without merging**
