### PR TITLE
Update info in QGIS and Esri section.

### PR DESCRIPTION
**Pull request by ankymtan**

### CODE REVIEW

**Comment by jyutzler** [comment]
@kryden do you concur with the changes to the Esri portion? If not, can you provide some alternate text?

**Comment by sfkeller** [comment]
Important addendum to the title of Section "QGIS" (just to be sure): 
The QGIS project decided to stick officially to "QGIS" (not "Quantum GIS").

**Comment by jyutzler** [comment]
In today's SWG we agreed to:
* reject this particular PR
* separately make the changes regarding QGIS as proposed and amended by @sfkeller 
* delegate the Esri section to an Esri representative (@kryden)

**Comment by sfkeller** [comment]
Hi Jeff. Thanks. That's fair enough. Now I hope Esri takes action :-)

**Pull request closed without merging**
