### PR TITLE
Clarify empty geometry flag

### LINKED ISSUE #502: Empty geometry flag seems to be unnecessary
The [Geometry Encoding](https://www.geopackage.org/spec121/index.html#gpb_format) includes an "empty geometry flag" specified as:

* Y: empty geometry flag
  * 0: non-empty geometry
  * 1: empty geometry

The specification does not define when this flag should be set or how this it should be interpreted. If the geometry is empty and is not a `POINT` then the WKB encoding of the geometry is sufficient to indicate that the geometry is empty. If the geometry is a `POINT EMPTY` then the specification already specifies how this should be handled (as a point with two quiet NaNs as its X and Y coordinates). Therefore, as far as I can tell, the "empty geometry flag" serves no purpose.

Proposal: deprecate the "empty geometry flag" and indicate that applications should ignore it.

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #502.

### CODE REVIEW

**Comment by twpayne** [comment]
Any chance of getting this merged?

**Comment by jyutzler** [comment]
We'll probably hold a SWG meeting later on this month, now that Testbed-15 is winding down.

**Comment by twpayne** [comment]
Great, thanks for the update.

**Comment by jyutzler** [comment]
As discussed in https://github.com/opengeospatial/geopackage/issues/502#issuecomment-576858448, we have determined that this pull request is not correct and will try again in #506.

**Pull request closed without merging**
